config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  frame sidebar
  # get 'sidebar', to: 'frames#sidebar'
  # get 'home', to: 'frames#home'

  #  master frame
  # root 'frames#main_index'
  resources :screens, only: [:show]

  resources :playlist, only: [] do
    resources :screens, only: [:show], controller: 'playlist_screens'
  end

  root to: redirect('/admin')
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
# frozen_string_literal: true

class Playlist < ApplicationRecord
  validates :name, presence: true
  validates :default_interval_sec, presence: true

  has_many :playlist_screens, dependent: :destroy
  has_many :screens, through: :playlist_screens
end

app/models/playlist_screen.rb
# frozen_string_literal: true

class PlaylistScreen < ApplicationRecord
  belongs_to :screen
  belongs_to :playlist
end

app/models/screen.rb
# frozen_string_literal: true

class Screen < ApplicationRecord
  validates :name, presence: true
  validates :link, presence: true

  has_many :playlist_screens, dependent: :destroy
  has_many :playlists, through: :playlist_screens
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/playlist_screens_controller.rb
# frozen_string_literal: true

class PlaylistScreensController < ApplicationController
  # Shows a single Screen - no context to a run
  def show
    playlist = Playlist.find(params[:playlist_id])
    @playlist_screen = playlist.playlist_screens.where(screen_id: params[:id]).first

    @next_playlist_screen = playlist.playlist_screens.where('id > ?', @playlist_screen.id).order('id ASC').first || playlist.playlist_screens.order('id ASC').first
  end
end

app/controllers/screens_controller.rb
# frozen_string_literal: true

class ScreensController < ApplicationController
  # Shows a single Screen - no context to a run
  def show
    @screen = Screen.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/screen_helper.rb
# frozen_string_literal: true

module ScreenHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScreenRotator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <% if content_for? :header_meta %>
      <%= yield :header_meta %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlist_screens/show.html.haml
-#this screen show is in context of a playlist - move to next item in list after interval

-#meta redirect
- content_for :header_meta do
  %meta{'http-equiv': "refresh", content: "#{@playlist_screen.interval_sec}; URL=#{playlist_screen_url(@next_playlist_screen.playlist, @next_playlist_screen.screen)}"}

= render '/screens/screen', screen: @playlist_screen.screen

app/views/screens/_screen.html.haml
%iframe{src: screen.link, style: "position: absolute; height: 100%; border: none; width: 100%; visibility:hidden;", onload: "this.style.visibility = 'visible';"}

app/views/screens/show.html.haml
-#= debug(@screen)

.topheader
  = link_to "Admin", admin_root_path
  - Screen.all.each do |screen|
    = link_to screen.id, screen_path(screen)

= render 'screen', screen: @screen